name: shared
description: Shared models and types for GeoWork application
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1 