// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMboKlZHplKNv5fxpkAVeXQS6Es4u5Q4',
    appId: '1:681589331619:web:22ff63704c062ee3c35116',
    messagingSenderId: '681589331619',
    projectId: 'geowork-time-tracker',
    authDomain: 'geowork-time-tracker.firebaseapp.com',
    storageBucket: 'geowork-time-tracker.firebasestorage.app',
    measurementId: 'G-ZXPR4NGT6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMboKlZHplKNv5fxpkAVeXQS6Es4u5Q4',
    appId: '1:681589331619:android:22ff63704c062ee3c35116',
    messagingSenderId: '681589331619',
    projectId: 'geowork-time-tracker',
    storageBucket: 'geowork-time-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDMboKlZHplKNv5fxpkAVeXQS6Es4u5Q4',
    appId: '1:681589331619:ios:22ff63704c062ee3c35116',
    messagingSenderId: '681589331619',
    projectId: 'geowork-time-tracker',
    storageBucket: 'geowork-time-tracker.firebasestorage.app',
    iosBundleId: 'com.yourcompany.geowork.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDMboKlZHplKNv5fxpkAVeXQS6Es4u5Q4',
    appId: '1:681589331619:macos:22ff63704c062ee3c35116',
    messagingSenderId: '681589331619',
    projectId: 'geowork-time-tracker',
    storageBucket: 'geowork-time-tracker.firebasestorage.app',
    iosBundleId: 'com.yourcompany.geowork.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMboKlZHplKNv5fxpkAVeXQS6Es4u5Q4',
    appId: '1:681589331619:windows:22ff63704c062ee3c35116',
    messagingSenderId: '681589331619',
    projectId: 'geowork-time-tracker',
    authDomain: 'geowork-time-tracker.firebaseapp.com',
    storageBucket: 'geowork-time-tracker.firebasestorage.app',
  );
} 